version: '3'
services: 
    front:
      build:
        context: './docker-react'
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      container_name: react-container
      environment:
        - WATCHPACK_POLLING=true
      networks:
        - mern-stack-networks
      volumes:
        - ./docker-react:/app
      depends_on:
      - backend

    backend:
      build: 
        context: './docker-nodejs'
        dockerfile: Dockerfile
      ports:
        - 5500:5500
      container_name: express-container

      networks:
        - mern-stack-networks
      volumes: 
        - ./docker-nodejs:/app
      depends_on:
        - mongo
    
    mongo:
      image: mongo
      ports:
        - 27017:27017
      container_name: mongo_container
      
      networks:
        - mern-stack-networks
      volumes:
        - mongoData:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=ecom

networks:
  mern-stack-networks:
volumes:
  mongoData:



